memsource/api.py
memsource/models.py
test/api/test_job.py
test/api/test_project.py
test/api/test_translation_memory.py

Depends on https://github.com/gengo/memsource-wrap/pull/12

Set trans memory api

---

README.rst

Required Python 3.4

---

memsource/api.py
memsource/memsource.py
memsource/models.py
test/api/test_analysis.py
test/api/test_asynchronouse.py
test/api/test_translation_memory.py

depends on https://github.com/gengo/memsource-wrap/pull/15/files
Implements
* aync create analysis
* get analysis

[#85986522] analysis get/async create

---

memsource/api.py

Use function anotations in BaseApi

---

memsource/lib/mxliff.py
memsource/models.py
requirements.txt
test/lib/mxliff/test.mxliff
test/lib/mxliff/test_mxliff_parser.py

[#86074764] Create mxliff parser

---

memsource/api.py
test/api/test_job.py

New method getBillingualAsMxliffUnits uses mxliff parser.

[#86278024] Parse billingual file

---

setup.py

We have to include lib directory.

Include lib directory in setup

---

memsource/api.py
test/api/test_job.py

Implements function for `getCompletedFile` endpoint.

[#87901500] combine

---

memsource/api.py

We can pass non requirements parameter for creating job.

Extra parameters

---

memsource/lib/mxliff.py

[#89683930] Return meta as str

---

memsource/__init__.py
memsource/api.py
memsource/exceptions.py
test/api/test_asynchronouse.py

We can uplaod docx, xlsx or any other memsource supporting format

[#98713596] Implement file uplaod functions

---

memsource/__init__.py
memsource/api.py
memsource/models.py
test/api/test_job.py

The function takes id of job_part list, returns the job data.

[#98912898] Make function for to get job data

---

memsource/__init__.py
memsource/api.py
test/api/test_translation_memory.py

Add next and previous segment parameter. 
http://wiki.memsource.com/wiki/Translation_Memory_API_v4#Search_Segment_By_Task

[#100616950] extra parameter for search segment by task

---

memsource/api.py

We can pass non required parameters

[#106358410] Support extra parameters for async analysis

---

memsource/__init__.py
memsource/api.py
memsource/constants.py
test/api/test_analysis.py
test/api/test_asynchronouse.py
test/api/test_client.py
test/api/test_domain.py
test/api/test_job.py
test/api/test_project.py
test/api/test_translation_memory.py
test/test_memsource.py

cloud1.memsource.com -> cloud.memsource.com

Follow Memsource API URL change

---

memsource/api.py
test/api/test_analysis.py
test/api/test_job.py

related pivotal story: https://www.pivotaltracker.com/story/show/113329923
This PR updates Memsource Wrap such that we include the *delete* endpoints for Job and Analysis.
References:
- Job: (http://wiki.memsource.com/wiki/Job_API_v7#Delete_Job)
- Analysis: (http://wiki.memsource.com/wiki/Analysis_API_v2#Delete_Analysis)

[#113329923] add delete endpoints for analysis and job

---

memsource/api.py

That API has many non required parameters. Keyword arguments are good for that I think.

[#112494021] Allow to path extra parameters for the searchSegmentByTask API

---

.gitignore
memsource/__init__.py
memsource/api.py
test/api/test_translation_memory.py

Added new endpoint for exporting translation memory data
http://wiki.memsource.com/wiki/Translation_Memory_API_v4#Export_Data

[#120260535] Add Translation memory export endpoint

---

CHANGELOG.rst
memsource/__init__.py
memsource/api.py
test/api/test_analysis.py
test/api/test_asynchronouse.py
test/api/test_client.py
test/api/test_domain.py
test/api/test_job.py
test/api/test_project.py
test/api/test_translation_memory.py
test/test_memsource.py

This library was using url parameter always.
It does not work well with large data. It looks the limit is 7KB.

Use request body in Post request

---

CHANGELOG.rst
memsource/api.py

This library had several style. Let's srandardlize it. Based on reStructuredText.

Standardize method comment style

---

.gitignore
.travis.yml
CHANGELOG.rst
memsource/__init__.py
memsource/api.py
setup.py
test/api/test_translation_memory.py

support endpoint https://wiki.memsource.com/wiki/Translation_Memory_API_v4#Search

[#146757471] Support TM search

---

memsource/api.py
memsource/models.py
test/api/test_language.py

* Add [Language API methods](https://wiki.memsource.com/wiki/Language_API_v2) to the wrapper
* Add tests unit for Language API

Wip/pierre peronnet/language api

---

CHANGELOG.rst
memsource/__init__.py
memsource/api.py
requirements.txt
test/api/test_project.py

- Support parameter filters on project list

Support parameter filters on project list

---

memsource/api.py
test/api/test_asynchronous.py

- implement asynchronous `Export By Query` function (https://wiki.memsource.com/wiki/Translation_Memory_Asynchronous_API_v2)

[#154831606] Async TM Export By Query function

---

memsource/api.py
memsource/constants.py
test/api/test_job.py

- Support `setStatus` endpoint on memsource
https://wiki.memsource.com/wiki/Job_API_v7#Set_Status

Support setStatus endpoint on memsource

---

CHANGELOG.rst
memsource/__init__.py
memsource/api.py
memsource/constants.py
test/api/test_analysis.py

- Support get analysis by project
https://wiki.memsource.com/wiki/Analysis_API_v2#List_Analyses_By_Project
- Support download anaylsis
https://wiki.memsource.com/wiki/Analysis_API_v2#Download_Analysis

Support get analysis by project and download anaylsis

---

CHANGELOG.rst
memsource/__init__.py
memsource/api.py
memsource/constants.py
memsource/models.py
requirements.txt
test/api/test_project.py
test/api/test_term_base.py

- Support retrieving term bases of a project - https://wiki.memsource.com/wiki/Project_API_v3#Get_Term_Bases
- Support downloading a term base - https://wiki.memsource.com/wiki/Term_Base_API_v2#Export_Data

Termbase methods

---

CHANGELOG.rst
memsource/__init__.py
memsource/api.py
memsource/memsource.py
test/test_memsource.py

Replace token and use JWT token as authentication if provided.

[#167217426] Use jwt token in headers as authentication if provided

---

CHANGELOG.rst
memsource/__init__.py
memsource/api.py
memsource/memsource.py
requirements.txt
test/api/test_asynchronous.py
test/api/test_base_api.py
test/api/test_client.py
test/api/test_domain.py
test/api/test_job.py
test/api/test_language.py
test/api/test_project.py
test/api/test_term_base.py
test/api/test_translation_memory.py
test/test_memsource.py

Refactor setting header,  there should be no logic changed.

Refactor headers

---

CHANGELOG.rst
memsource/__init__.py
memsource/api.py

Add `page` param for `listByProject`

[SE-218] Return all jobs from all pages

---

CHANGELOG.rst
README.rst
memsource/__init__.py
memsource/api_rest.py
memsource/constants.py
test/api/test_job.py
test/api_rest/test_base_api.py

- This PR introduces a new Base class for the Memsource REST api.
- Inheriting classes are the different resources (Jobs, Translation Memories, Analysis, etc.) and will be pushed in smaller PRs.

Base api for rest transition

---

CHANGELOG.rst
memsource/__init__.py
memsource/api_rest/__init__.py
memsource/api_rest/auth.py
memsource/api_rest/client.py
test/api_rest/test_auth.py
test/api_rest/test_client.py

- Introduce an Auth and Client class that will use the new Memsource REST API. For now, we will only support what we already have.
https://github.com/gengo/memsource-wrap/blob/41927abe1fe74e95d7eee8f88cf352a303ca5317/memsource/api.py#L217-L254
- https://cloud.memsource.com/web/docs/api#tag/Authentication
- https://cloud.memsource.com/web/docs/api#tag/Client

Rest auth client class

---

CHANGELOG.rst
memsource/__init__.py
memsource/api_rest/domain.py
memsource/api_rest/language.py
memsource/api_rest/term_base.py
memsource/constants.py
test/api_rest/test_domain.py
test/api_rest/test_language.py
test/api_rest/test_term_base.py

- Introduce a Domain, Language and Term Base class that will use the new Memsource REST API.
- For now, we will only support what we already have.
https://github.com/gengo/memsource-wrap/blob/41927abe1fe74e95d7eee8f88cf352a303ca5317/memsource/api.py#L257-L291
https://github.com/gengo/memsource-wrap/blob/41927abe1fe74e95d7eee8f88cf352a303ca5317/memsource/api.py#L1075-L1105

Rest Domain Language and Term Base class

---

CHANGELOG.rst
memsource/__init__.py
memsource/api_rest/__init__.py
memsource/api_rest/project.py
memsource/constants.py
test/api_rest/test_project.py

- Introduce a Project class that will use the new Memsource REST API.
- Introduce a `_put` method that will handle PUT requests.
- Some Memsource resources returns 204 for a POST request which `response.json()` throws an error. Handle this by checking if the status_code is 204 and return an empty dictionary instead. [Requests.json()](https://requests.readthedocs.io/en/master/user/quickstart/#json-response-content)
- For now, we will only support what we already have.
https://github.com/gengo/memsource-wrap/blob/41927abe1fe74e95d7eee8f88cf352a303ca5317/memsource/api.py#L294-L382

REST project class

---

CHANGELOG.rst
memsource/__init__.py
memsource/api_rest/__init__.py
memsource/api_rest/bilingual.py
memsource/api_rest/job.py
test/api_rest/test_bilingual.py

- New Bilingual class to house all bilingual file related endpoints.
- Introduce a Job class that will use the new Memsource REST API.
- Introduce a `_post_stream` method that will handle POST requests returning the raw response instead of a json

New Bilingual class

---

CHANGELOG.rst
memsource/__init__.py
memsource/api_rest/tm.py
test/api_rest/test_tm.py

- Introduce a TranslationMemory class that will use the new Memsource REST API.
- For now, we will only support what we already have.
https://github.com/gengo/memsource-wrap/blob/bd6db2e866ae5ca0e66aca5e77ea44af716d9a3a/memsource/api.py#L626-L810

REST TranslationMemory class
